name: Azure Resource Cleanup

on:
  workflow_dispatch:  # This allows manual triggering

env:
  AZURE_RESOURCE_GROUP: test
  VM_NAME: myVM

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Azure VM
      run: |
        az vm delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.VM_NAME }} \
          --yes 
    
    - name: Delete Network Interface
      run: |
        az network nic delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${VM_NAME}VMNic

    - name: Delete Network Security Group
      run: |
        az network nsg delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${VM_NAME}-nsg 

    - name: Delete Public IP
      run: |
        az network public-ip delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${VM_NAME}PublicIP

    - name: Delete Virtual Network
      run: |
        az network vnet delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${VM_NAME}VNET
    
    - name: Delete Orphaned Disks
      run: |
        ORPHANED_DISKS=$(az disk list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[?tags.VMName=='${VM_NAME}'].id" -o tsv)
        for DISK in $ORPHANED_DISKS; do
          az disk delete --ids $DISK --yes
        done
